name: app-environment
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.8
  - pyqt>=5.15.0
  - opencv>=4.5.0
  - numpy>=1.21.0
  - pydantic>=2.0.0
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - pip
  - pip:
    - ultralytics>=8.0.0 