# YOLO Training Configuration for Armored Vehicles
        # Model configuration
        model: yolov8s.pt
        data: annotated_data/dataset.yaml

        # Training parameters
        epochs: 100
        batch_size: 16
        imgsz: 512

        # Optimization
        lr0: 0.01
        lrf: 0.01
        momentum: 0.937
        weight_decay: 0.0005
        warmup_epochs: 3.0
        warmup_momentum: 0.8
        warmup_bias_lr: 0.1

        # Augmentation
        hsv_h: 0.015
        hsv_s: 0.7
        hsv_v: 0.4
        degrees: 0.0
        translate: 0.1
        scale: 0.5
        shear: 0.0
        perspective: 0.0
        flipud: 0.0
        fliplr: 0.5
        mosaic: 1.0
        mixup: 0.0
        copy_paste: 0.0

        # Loss coefficients
        box: 7.5
        cls: 0.5
        dfl: 1.5
        pose: 12.0
        kobj: 1.0
        label_smoothing: 0.0

        # Save and validation
        save_period: -1
        save_dir: runs/train
        cache: False
        device: device=1    
        workers: 0
        project: armored_vehicles_detection
        name: exp
        exist_ok: False
        pretrained: True
        optimizer: auto
        verbose: True
        seed: 0
        deterministic: True
        single_cls: False
        rect: False
        cos_lr: False
        close_mosaic: 10
        resume: False
        amp: True
        fraction: 1.0
        profile: False
        freeze: None
        multi_scale: False

        # Validation
        val: True
        plots: True
