CLASSES = {
    "ARMED_POLICEMEN": ["Police officer holding a firearm, Police man with weapon"],
    "ATTACK": ["military attack", "drone attack"],
    "FIRE": ["Visible flames or blaze", "Fire"],
   # "FIREFIGHTER": ["Person in firefighting gear", "Firefighter"],
    "FIRE_TRUCK": ["Firefighting vehicle, fire brigade truck"],
   # "HEALTH_AMBULANCE": ["Emergency medical vehicle, ambulance"],
    "IMMIGRANT": ["Group in transit or migration context"],
    "MILITARY_OFFICER": ["Military personnel with rank insignia"],
    "MILITARY_SOLDIER": ["Army soldier in uniform"],
    "MILITARY_VEHICLE": ["Armored military vehicle, tank"],
    "POLICE": ["Law enforcement personnel", "police man", "Uniformed police officer"],
    "POLICE_VEHICLE": ["Police vehicle", "Police car", "Police Truck"],
    # "PRISON": ["Incarceration facility or prison structure"],
    # "PROTEST": ["Crowd demonstrating with signs or banners"],
    "PROTESTOR": ["Protestor demonstrating with signs or banners"],
    #"RIOT": ["Violent or chaotic protest scene"],
    "RIOT_POLICE": ["Police in riot gear, shields, and helmets"],
    #"TEARGAS": ["Cloud of gas or tear gas canister in crowd"],
    "WEAPON": ["police gun", "police weapon", "rifle", "military gun"]
}