services:
  fastapi:
    build: .
    ports:
      - "8814:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ../../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - TORCH_HOME=/app/torch
      - HF_HOME=/app/transformers
    stdin_open: true
    tty: true
